### ISSUE TITLE
Provide a way to unbind handler

### ISSUE THREAD

**Issue by xobotyi** [tcardlab/rsHook#1]
First of all - thanks for the library, it saved my day after inability to use (even build myself) iohook package with latest electron versions.

My current concern is power consumption and the fact that once being added - there is no way to unbind callback.

It would be great if method to unbind handler will be added so there are no napi calls occur when it is not needed.

**Comment by tcardlab** [comment]
Unfortunately, this is not a production ready repo (just a proof of concept). 
Unless you plan to maintain your own fork, I would consider other options.

I agree that [ioHook](https://github.com/wilix-team/iohook) is in a rather sad state. However, its just a binding for [libuiohook](https://github.com/kwhat/libuiohook). 
There is an up and coming alternative, [uiohook-napi](https://github.com/SnosMe/uiohook-napi). As you can see [here](https://github.com/SnosMe/uiohook-napi/blob/63745a540828de230392eee3e6cf85d8a4d09e13/src/index.ts#L245), it supports termination.

<br/>

If you insistent on leaving the libuiohook ecosystem for Rust based solutions:
1) I do not believe [rdev](https://github.com/Narsil/rdev) has a means to terminate. (If you find I'm mistaken, please let me know!)
2) There has been much community development on rdev since this was made, particularly on the [fufesou-fork](https://github.com/fufesou/rdev)

So i would suggest making an issue on one of those repos. 

<br/>

Alternatively, you may be able to add termination with a child process and avoid napi and rsHook all together:
```js
/* UNTESTED CODE: a guess at best */
let child;
let cmd = 'rdevScript.exe'  // along the lines of https://github.com/Narsil/rdev/blob/main/examples/listen.rs

function killSpawn() {
  if (!child) return // don't kill undef...

  // Safely closes existing child process
  child.stdin.end()
  child.kill()  // Filicide
}

function callback(s) {
  // parse "s" and send to wherever.
}

function onErr(s) {
  console.log("rdevErr:", s)
  killSpawn()
}

function initSpawn() {
  if (child) killSpawn(); // or just return, up to you.

  child = spawn(cmd);  

  child.stdout.on('data', out => {
    callback(out.toString())
  });
  child.stderr.on('data', out => {
    onErr(out.toString())
  });
}

initSpawn()
```

<br>

As for rsHook, I don't know of any way to terminate a napi/bindgen process from js (and most of the bindings are autogenerated).
Additionally, at least on mac, the rdev listener must be on main thread. this is a blocking process, so even termination on the rust end may be tricky...

<br>

I hope you've found something helpful in all this. 
Goode luck!

**Comment by tcardlab** [comment]
I added an example in the [spawn](https://github.com/tcardlab/rsHook/tree/spawn) branch, in case you wanted to go that route.
However, [uiohook-napi](https://github.com/SnosMe/uiohook-napi) is still probably your best choice at the moment.

**Comment by tcardlab** [comment]
lol, wasn't expecting this to closed a year later

Out of curiosity, did you use this or find an input hook to suit your needs?

(In other news, iohook just got a new maintainer, so thats interesting. Repo still doesn't seem very active, but there are a handful of forks for current builds. Uiohook-napi still seems to have issues on mac as far as I know...)
